<a href="https://colab.research.google.com/github/tlonge26/trade-finance-logistics/blob/master/Training_data_with_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 3



In [ ]:
import pandas as pd
#Reading of the data cell
data = pd.read_excel("/content/Week6 - WellsFargo_Unstructured (1).xlsx")
data

message_id           timestamp  \
0     774389429725170944 2016-09-09 16:30:00   
1     774377609123794048 2016-09-09 15:43:00   
2     774396897117298048 2016-09-09 16:59:00   
3     774372542672875008 2016-09-09 15:22:00   
4     774388241386482944 2016-09-09 16:25:00   
...                  ...                 ...   
9181         LO-OYLxpRzE 2016-10-04 00:00:00   
9182         LO-OYLxpRzE 2016-10-04 00:00:00   
9183         LO-OYLxpRzE 2016-10-04 00:00:00   
9184         LO-OYLxpRzE 2016-10-04 00:00:00   
9185         LO-OYLxpRzE 2016-10-04 00:00:00   

                                            messageText  CleanedText  
0     [<strong>Wells Fargo</strong>, ' fined $185 mi...          NaN  
1     [<strong>Wells Fargo</strong>, ' fined $100 mi...          NaN  
2     ["Why Aren't Exec Heads Rolling at ", <strong>...          NaN  
3     ['Fake accounts put focus on ', <strong>Wells ...          NaN  
4     [<strong>Wells Fargo</strong>, ' blaming emplo...          NaN  
...                                                 ...          ...  
9181  this video page is like a freakn.virus. I have...          NaN  
9182                         please do more isis stuff.          NaN  
9183  American prisons are the most comfortable pris...          NaN  
9184  aww the murderer has poor living conditions. h...          NaN  
9185  Don't like prison? Don't murder people ( <U+03...          NaN  

[9186 rows x 4 columns]

In [ ]:
"""Using regular expression in python allows us to remove unwanted characters.
I imported the re from python which is the regular expression. I created a funtion
called CleanText which takes in the dataset that I want to clean. The first line
that I checked if the data is a test and a string value, if it is then I used a
regualr expression to remove HTTP,spaces, special character.   """

import re
def clean_text(text):
    if not isinstance(text, str):
        text = str(text)

    # Remove Hyperlinks
    text = re.sub(r'http\S+', '', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove Foreign Language Characters
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    # Remove Spaces and Whitespaces
    text = ' '.join(text.split())

    return text
"""I created a column in my dataset called CleanedData and I applied the clenText
function that I created above on the messageText column which allows my data to
be cleaned. I saved my CleanedData set with a name called clean_data.csv"""
data['CleanedData'] = data['messageText'].apply(clean_text)
#data.to_csv('cleaned_data.csv', index=False)


In [ ]:
data

message_id           timestamp  \
0     774389429725170944 2016-09-09 16:30:00   
1     774377609123794048 2016-09-09 15:43:00   
2     774396897117298048 2016-09-09 16:59:00   
3     774372542672875008 2016-09-09 15:22:00   
4     774388241386482944 2016-09-09 16:25:00   
...                  ...                 ...   
9181         LO-OYLxpRzE 2016-10-04 00:00:00   
9182         LO-OYLxpRzE 2016-10-04 00:00:00   
9183         LO-OYLxpRzE 2016-10-04 00:00:00   
9184         LO-OYLxpRzE 2016-10-04 00:00:00   
9185         LO-OYLxpRzE 2016-10-04 00:00:00   

                                            messageText  CleanedText  \
0     [<strong>Wells Fargo</strong>, ' fined $185 mi...          NaN   
1     [<strong>Wells Fargo</strong>, ' fined $100 mi...          NaN   
2     ["Why Aren't Exec Heads Rolling at ", <strong>...          NaN   
3     ['Fake accounts put focus on ', <strong>Wells ...          NaN   
4     [<strong>Wells Fargo</strong>, ' blaming emplo...          NaN   
...                                                 ...          ...   
9181  this video page is like a freakn.virus. I have...          NaN   
9182                         please do more isis stuff.          NaN   
9183  American prisons are the most comfortable pris...          NaN   
9184  aww the murderer has poor living conditions. h...          NaN   
9185  Don't like prison? Don't murder people ( <U+03...          NaN   

                                            CleanedData  
0     [Wells Fargo, ' fined $185 million in penaltie...  
1     [Wells Fargo, ' fined $100 million for illegal...  
2     ["Why Aren't Exec Heads Rolling at ", Wells Fa...  
3     ['Fake accounts put focus on ', Wells Fargo, '...  
4     [Wells Fargo, ' blaming employees is "biggest ...  
...                                                 ...  
9181  this video page is like a freakn.virus. I have...  
9182                         please do more isis stuff.  
9183  American prisons are the most comfortable pris...  
9184  aww the murderer has poor living conditions. h...  
9185         Don't like prison? Don't murder people ( )  

[9186 rows x 5 columns]

In [ ]:
data = data.drop('CleanedText',axis = 1)
data

message_id           timestamp  \
0     774389429725170944 2016-09-09 16:30:00   
1     774377609123794048 2016-09-09 15:43:00   
2     774396897117298048 2016-09-09 16:59:00   
3     774372542672875008 2016-09-09 15:22:00   
4     774388241386482944 2016-09-09 16:25:00   
...                  ...                 ...   
9181         LO-OYLxpRzE 2016-10-04 00:00:00   
9182         LO-OYLxpRzE 2016-10-04 00:00:00   
9183         LO-OYLxpRzE 2016-10-04 00:00:00   
9184         LO-OYLxpRzE 2016-10-04 00:00:00   
9185         LO-OYLxpRzE 2016-10-04 00:00:00   

                                            messageText  \
0     [<strong>Wells Fargo</strong>, ' fined $185 mi...   
1     [<strong>Wells Fargo</strong>, ' fined $100 mi...   
2     ["Why Aren't Exec Heads Rolling at ", <strong>...   
3     ['Fake accounts put focus on ', <strong>Wells ...   
4     [<strong>Wells Fargo</strong>, ' blaming emplo...   
...                                                 ...   
9181  this video page is like a freakn.virus. I have...   
9182                         please do more isis stuff.   
9183  American prisons are the most comfortable pris...   
9184  aww the murderer has poor living conditions. h...   
9185  Don't like prison? Don't murder people ( <U+03...   

                                            CleanedData  
0     [Wells Fargo, ' fined $185 million in penaltie...  
1     [Wells Fargo, ' fined $100 million for illegal...  
2     ["Why Aren't Exec Heads Rolling at ", Wells Fa...  
3     ['Fake accounts put focus on ', Wells Fargo, '...  
4     [Wells Fargo, ' blaming employees is "biggest ...  
...                                                 ...  
9181  this video page is like a freakn.virus. I have...  
9182                         please do more isis stuff.  
9183  American prisons are the most comfortable pris...  
9184  aww the murderer has poor living conditions. h...  
9185         Don't like prison? Don't murder people ( )  

[9186 rows x 4 columns]

In [ ]:
data

message_id           timestamp  \
0     774389429725170944 2016-09-09 16:30:00   
1     774377609123794048 2016-09-09 15:43:00   
2     774396897117298048 2016-09-09 16:59:00   
3     774372542672875008 2016-09-09 15:22:00   
4     774388241386482944 2016-09-09 16:25:00   
...                  ...                 ...   
9181         LO-OYLxpRzE 2016-10-04 00:00:00   
9182         LO-OYLxpRzE 2016-10-04 00:00:00   
9183         LO-OYLxpRzE 2016-10-04 00:00:00   
9184         LO-OYLxpRzE 2016-10-04 00:00:00   
9185         LO-OYLxpRzE 2016-10-04 00:00:00   

                                            messageText  \
0     [<strong>Wells Fargo</strong>, ' fined $185 mi...   
1     [<strong>Wells Fargo</strong>, ' fined $100 mi...   
2     ["Why Aren't Exec Heads Rolling at ", <strong>...   
3     ['Fake accounts put focus on ', <strong>Wells ...   
4     [<strong>Wells Fargo</strong>, ' blaming emplo...   
...                                                 ...   
9181  this video page is like a freakn.virus. I have...   
9182                         please do more isis stuff.   
9183  American prisons are the most comfortable pris...   
9184  aww the murderer has poor living conditions. h...   
9185  Don't like prison? Don't murder people ( <U+03...   

                                            CleanedData  
0     [Wells Fargo, ' fined $185 million in penaltie...  
1     [Wells Fargo, ' fined $100 million for illegal...  
2     ["Why Aren't Exec Heads Rolling at ", Wells Fa...  
3     ['Fake accounts put focus on ', Wells Fargo, '...  
4     [Wells Fargo, ' blaming employees is "biggest ...  
...                                                 ...  
9181  this video page is like a freakn.virus. I have...  
9182                         please do more isis stuff.  
9183  American prisons are the most comfortable pris...  
9184  aww the murderer has poor living conditions. h...  
9185         Don't like prison? Don't murder people ( )  

[9186 rows x 4 columns]

# Question 4

In [4]:
import pandas as pd
data = pd.read_excel('/content/Week6_fraud_data_small.xlsx')
data



Unnamed: 0 trans_date_trans_time            cc_num  \
0                0   2020-06-21 12:14:25  2291163933867240   
1                1   2020-06-21 12:14:33  3573030041201290   
2                2   2020-06-21 12:14:53  3598215285024750   
3                3   2020-06-21 12:15:15  3591919803438420   
4                4   2020-06-21 12:15:17  3526826139003040   
...            ...                   ...               ...   
555714      555714   2020-12-31 23:59:07    30560609640617   
555715      555715   2020-12-31 23:59:09  3556613125071650   
555716      555716   2020-12-31 23:59:15  6011724471098080   
555717      555717   2020-12-31 23:59:24     4079773899158   
555718      555718   2020-12-31 23:59:34  4170689372027570   

                                    merchant        category     amt    first  \
0                      fraud_Kirlin and Sons   personal_care    2.86     Jeff   
1                       fraud_Sporer-Keebler   personal_care   29.84   Joanne   
2       fraud_Swaniawski, Nitzsche and Welch  health_fitness   41.28   Ashley   
3                          fraud_Haley Group        misc_pos   60.05    Brian   
4                      fraud_Johnston-Casper          travel    3.19   Nathan   
...                                      ...             ...     ...      ...   
555714                 fraud_Reilly and Sons  health_fitness   43.77  Michael   
555715                  fraud_Hoppe-Parisian       kids_pets  111.84     Jose   
555716                       fraud_Rau-Robel       kids_pets   86.88      Ann   
555717                 fraud_Breitenberg LLC          travel    7.99     Eric   
555718                     fraud_Dare-Marvin   entertainment   38.13   Samuel   

            last gender                       street  ...      lat      long  \
0        Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1       Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2          Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3       Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4         Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   
...          ...    ...                          ...  ...      ...       ...   
555714     Olson      M          558 Michael Estates  ...  40.4931  -91.8912   
555715   Vasquez      M          572 Davis Mountains  ...  29.0393  -95.4401   
555716    Lawson      F   144 Evans Islands Apt. 683  ...  46.1966 -118.9017   
555717   Preston      M   7020 Doyle Stream Apt. 951  ...  44.6255 -116.4493   
555718      Frey      M     830 Myers Plaza Apt. 384  ...  35.6665  -97.4798   

        city_pop                     job        dob  \
0         333497     Mechanical engineer 1968-03-19   
1            302  Sales professional, IT 1990-01-17   
2          34496       Librarian, public 1970-10-21   
3          54767            Set designer 1987-07-25   
4           1126      Furniture designer 1955-07-06   
...          ...                     ...        ...   
555714       519            Town planner 1966-02-13   
555715     28739          Futures trader 1999-12-27   
555716      3684                Musician 1981-11-29   
555717       129            Cartographer 1965-12-15   
555718    116001             Media buyer 1993-05-10   

                               trans_num   unix_time  merch_lat  merch_long  \
0       2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1       324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2       c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3       2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4       57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   
...                                  ...         ...        ...         ...   
555714  9b1f753c79894c9f4b71f04581835ada  1388534347  39.946837  -91.333331   
555715  2090647dac2c89a1d86c514c427f

In [5]:
data.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [7]:
data = data.drop(['trans_date_trans_time','dob','trans_num','unix_time'],axis = 1)
data.columns

Index(['Unnamed: 0', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last',
       'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop',
       'job', 'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix




# Data Cleaning and Feature Engineering
# Convert categorical variables to numeric using LabelEncoder
label_encoder = LabelEncoder()

# Assuming 'merchant', 'category', 'gender', and 'job' are categorical variables
categorical_columns = ['merchant', 'category', 'gender', 'job']

for col in categorical_columns:
    data[col] = label_encoder.fit_transform(data[col])

# Drop unnecessary columns (e.g., 'first', 'last', 'street', etc.)
data = data.drop(['first', 'last', 'street', 'city', 'state'], axis=1)

data = data.fillna(0)

# Split the data into features (X) and target variable (y)
X = data.drop('is_fraud', axis=1)
y = data['is_fraud']

# Check unique values in the target variable
unique_values = y.unique()
print(f'Unique values in the target variable: {unique_values}')

# Handle imbalanced classes (if necessary)
# You can use techniques like oversampling, undersampling, or class weights
# Example: Using class weights
class_weights = dict(zip(unique_values, len(y) / (len(unique_values) * pd.Series(y).value_counts())))
print(f'Class Weights: {class_weights}')

from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist["data"], mnist["target"]
y = y.astype(np.uint8)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the SVM model
svm_model = SVC(kernel='linear', C=1.0, class_weight=class_weights, random_state=42)

svm_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{classification_rep}')

Unique values in the target variable: [0 1]
Class Weights: {0: 0.5019374103552551, 1: 129.53822843822843}


/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Accuracy: 0.9187445887445888
Confusion Matrix:
[[2189    1   12    5    6   22   22    2    6    2]
 [   0 2551   12    8    1    4    0    5   18    4]
 [  25   39 2114   44   32    8   26   21   34    7]
 [  11    8   66 2169    4   63    1   15   27   19]
 [   5    6   28    3 2019    2    7   11    4   59]
 [  24   18   15  109   12 1852   22    5   37   13]
 [  13    8   49    4   32   38 2145    1    4    0]
 [   4   12   47   22   33    9    0 2270    4   54]
 [  24   42   45   80    7   63   17   13 1875   30]
 [  11   23   23   22   82    9    0   68   24 2039]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96      2267
           1       0.94      0.98      0.96      2603
           2       0.88      0.90      0.89      2350
           3       0.88      0.91      0.89      2383
           4       0.91      0.94      0.92      2144
           5       0.89      0.88      0.89      2107
           6       0

# Explanation of the output of our Trained Model.

In [ ]:
# Accuracy: 0.9187445887445888
"""Accuracy is the measure of the overall correctness of the model. In this case,
the model achieved an accuracy of approximately 91.87%, meaning it is correctly
classified about 91.87% of the instances in the test set."""

# Confusion Matrix:

"""[[2189    1   12    5    6   22   22    2    6    2]
 [   0 2551   12    8    1    4    0    5   18    4]
 [  25   39 2114   44   32    8   26   21   34    7]
 [  11    8   66 2169    4   63    1   15   27   19]
 [   5    6   28    3 2019    2    7   11    4   59]
 [  24   18   15  109   12 1852   22    5   37   13]
 [  13    8   49    4   32   38 2145    1    4    0]
 [   4   12   47   22   33    9    0 2270    4   54]
 [  24   42   45   80    7   63   17   13 1875   30]
 [  11   23   23   22   82    9    0   68   24 2039]]
 A confusion matrix provides a detailed breakdown of the model's predictions.
 Each row represents the actual class, and each column represents the predicted
 class. The diagonal element represents the number of correct predictions for
 each class.

 Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96      2267
           1       0.94      0.98      0.96      2603
           2       0.88      0.90      0.89      2350
           3       0.88      0.91      0.89      2383
           4       0.91      0.94      0.92      2144
           5       0.89      0.88      0.89      2107
           6       0.96      0.94      0.95      2294
           7       0.94      0.92      0.93      2455
           8       0.92      0.85      0.89      2196
           9       0.92      0.89      0.90      2301

    accuracy                           0.92     23100
   macro avg       0.92      0.92      0.92     23100
weighted avg       0.92      0.92      0.92     23100

The classification report provides precision, recall, and F1-score for each
class, as well as their averages.
Precision is the ratio of correctly predicted positive observation to the total
predicted positives. Recall (sensitivity) is the ratio of correctly positive
observation to the actual positives.
F1-score is the harmonic mean of precision and recall.
Overall, the model shows good performance across multiple classes,with high
accuracy and balanced decision and recall values."""
